name: Test
on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-18.04
    container:
      image: acesdev/algo-base:awscli2.1.25-poetry1.1.4-tensorrt7.2.2-python3.8.7-cuda11.0-cudnn8-devel-ubuntu18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install pip packages
        run: |
          pip install --upgrade pip
          poetry install --no-root
      - name: Lint with flake8
        run: |
          flake8 --version
          isort --version
          flake8 --count --show-source --statistics
      - name: Test
        run: |
          python -m unittest
